### ISSUE TITLE
maybe error for vllm 0.6.3

### ISSUE THREAD

**Issue by zoumf709** [winter1203/vllm_GOT2_OCR#1]
非常感谢作者的无私奉献！！！！
1、运用vllm加速很明显，但是，还是挺慢的，一张A4的图片，需要7秒钟！！
2、在vllm0.6.3的环境下，识别结果错误比0.5.3上多，并且同一张图，v0.5.3上需要7.1s，但是v0.6.3上需要11s
作者在新版本的vllm上适配过没有？

**Comment by winter1203** [comment]
1. 这个版本只适配了0.5.3的版本
2. 建议将图片分成多张小图，原论文作者团队并未为vary encoder 部分加速,也就是说视觉部分没有进行加速，后续可能补上这部分的加速。
